/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SVRF) {
      root.SVRF = {};
    }
    root.SVRF.MediaType = factory(root.SVRF.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class MediaType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "photo"
     * @const
     */
    "photo": "photo",
    /**
     * value: "video"
     * @const
     */
    "video": "video",
    /**
     * value: "3d"
     * @const
     */
    "3d": "3d"  };

  /**
   * Returns a <code>MediaType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/MediaType} The enum <code>MediaType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


