/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SVRF) {
      root.SVRF = {};
    }
    root.SVRF.RateLimitResponse = factory(root.SVRF.ApiClient, root.SVRF.ErrorResponse);
  }
}(this, function(ApiClient, ErrorResponse) {
  'use strict';




  /**
   * The RateLimitResponse model module.
   * @module model/RateLimitResponse
   * @version 1.5.0
   */

  /**
   * Constructs a new <code>RateLimitResponse</code>.
   * @alias module:model/RateLimitResponse
   * @class
   * @implements module:model/ErrorResponse
   */
  var exports = function() {
    var _this = this;

    ErrorResponse.call(_this);

  };

  /**
   * Constructs a <code>RateLimitResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateLimitResponse} obj Optional instance to populate.
   * @return {module:model/RateLimitResponse} The populated <code>RateLimitResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      ErrorResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * Error message
   * @member {String} message
   */
  exports.prototype['message'] = undefined;

  // Implement ErrorResponse interface:
  /**
   * Error message
   * @member {String} message
   */
exports.prototype['message'] = undefined;

  /**
   * If the request was successful
   * @member {Boolean} success
   */
exports.prototype['success'] = undefined;



  return exports;
}));


