/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthResponse', 'model/Body', 'model/ErrorResponse', 'model/RateLimitResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AuthResponse'), require('../model/Body'), require('../model/ErrorResponse'), require('../model/RateLimitResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SVRF) {
      root.SVRF = {};
    }
    root.SVRF.AuthenticateApi = factory(root.SVRF.ApiClient, root.SVRF.AuthResponse, root.SVRF.Body, root.SVRF.ErrorResponse, root.SVRF.RateLimitResponse);
  }
}(this, function(ApiClient, AuthResponse, Body, ErrorResponse, RateLimitResponse) {
  'use strict';

  /**
   * Authenticate service.
   * @module api/AuthenticateApi
   * @version 1.4.0
   */

  /**
   * Constructs a new AuthenticateApi. 
   * @alias module:api/AuthenticateApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Authenticate application
     * Authenticate an application&#39;s SVRF API Key to retrieve an access token to the SVRF API.
     * @param {module:model/Body} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AuthResponse} and HTTP response
     */
    this.authenticateWithHttpInfo = function(body) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling authenticate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AuthResponse;

      return this.apiClient.callApi(
        '/app/authenticate', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Authenticate application
     * Authenticate an application&#39;s SVRF API Key to retrieve an access token to the SVRF API.
     * @param {module:model/Body} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AuthResponse}
     */
    this.authenticate = function(body) {
      return this.authenticateWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
