/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SVRF);
  }
}(this, function(expect, SVRF) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SVRF.MediaVideos();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MediaVideos', function() {
    it('should create an instance of MediaVideos', function() {
      // uncomment below and update the code to test MediaVideos
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be.a(SVRF.MediaVideos);
    });

    it('should have the property _848 (base name: "848")', function() {
      // uncomment below and update the code to test the property _848
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property _1440 (base name: "1440")', function() {
      // uncomment below and update the code to test the property _1440
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property _2160 (base name: "2160")', function() {
      // uncomment below and update the code to test the property _2160
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property _4096 (base name: "4096")', function() {
      // uncomment below and update the code to test the property _4096
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property clip (base name: "clip")', function() {
      // uncomment below and update the code to test the property clip
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property hls (base name: "hls")', function() {
      // uncomment below and update the code to test the property hls
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instane = new SVRF.MediaVideos();
      //expect(instance).to.be();
    });

  });

}));
