/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SVRF);
  }
}(this, function(expect, SVRF) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SVRF.MediaFiles();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MediaFiles', function() {
    it('should create an instance of MediaFiles', function() {
      // uncomment below and update the code to test MediaFiles
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be.a(SVRF.MediaFiles);
    });

    it('should have the property glb (base name: "glb")', function() {
      // uncomment below and update the code to test the property glb
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

    it('should have the property glbDraco (base name: "glb-draco")', function() {
      // uncomment below and update the code to test the property glbDraco
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

    it('should have the property gltf (base name: "gltf")', function() {
      // uncomment below and update the code to test the property gltf
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

    it('should have the property stereo (base name: "stereo")', function() {
      // uncomment below and update the code to test the property stereo
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

    it('should have the property videos (base name: "videos")', function() {
      // uncomment below and update the code to test the property videos
      //var instane = new SVRF.MediaFiles();
      //expect(instance).to.be();
    });

  });

}));
